version: '3'
services:
  
  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: admindb
      MYSQL_USER: admin
      MYSQL_PASSWORD: "password"
    cap_add:
      - SYS_NICE
    volumes:
      - mysql-data:/var/lib/mysql
volumes: 
  mysql-data:
